\NeedsTeXFormat{LaTeX2e}[1996/06/01]
\ProvidesClass{ButtonLegends}
	      [2012/02/29 v0.1]
\setlength\paperheight {8.5in} \setlength\paperwidth  {11in}
\setlength\pdfpageheight{8.5in} \setlength\pdfpagewidth{11in}
\input{size10.clo}
\setlength\lineskip{1\p@}
\setlength\normallineskip{1\p@}
\renewcommand\baselinestretch{}
\setlength\parskip{0pt}
\setlength\parindent{0pt}
\setlength\textwidth{720pt}
\setlength\textheight{540pt}
\setlength\oddsidemargin{-36pt}
\setlength\evensidemargin{-36pt}
\setlength\marginparwidth{0pt}
\setlength\topmargin{-36pt}
\setlength\headheight{0pt}
\setlength\headsep{0pt}
\setlength\footskip{0pt}
%\global\pdfpageattr{/Rotate -90}
\newcommand\legend[1]{\framebox[50.92pt][c]{\rule{0pt}{20pt}#1}}
\endinput

